# Generated by Django 4.2.11 on 2024-04-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_park_alter_feeding_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='park',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
